import "./globals.css";
import Providers from "./redux/Provider";
import Header from "@/components/Header";

export const metadata = {
  title: "Amazon 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
